name: Build and Test Webserv

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Webserv Docker image
        run: docker build -t webserv .

      - name: Start Webserv container
        run: |
          docker run -d --name webserv_container2 -p 8080:8080 webserv

      - name: Wait for Webserv to be ready
        run: |
          echo "Waiting for server on ports 8080..."
          for port in 8080; do
            until nc -z localhost $port; do
              echo "Waiting for port $port..."
              sleep 0.2
            done
          done
          echo "Server is ready!"

      - name: Run tests
        run: ./test_webserv.sh

      - name: Stop Webserv container
        run: docker stop webserv_container && docker rm webserv_container
